OPEN-ENT-NG/vie-scolaire

- .github/workflows/dev-check-repository.yml
- src/main/java/fr/openent/Viescolaire.java
- src/main/java/fr/openent/viescolaire/controller/EventBusController.java
- src/main/java/fr/openent/viescolaire/controller/MultiTeachingController.java
- src/main/java/fr/openent/viescolaire/helper/MultiTeachingHelper.java
- src/main/java/fr/openent/viescolaire/model/MultiTeaching.java
- src/main/java/fr/openent/viescolaire/service/CommonCoursService.java
- src/main/java/fr/openent/viescolaire/service/MultiTeachingService.java
- src/main/java/fr/openent/viescolaire/service/UtilsService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultCommonCoursService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultMatiereService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultMultiTeachingService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultUtilsService.java
- src/main/java/fr/openent/viescolaire/utils/DateHelper.java
- src/main/java/fr/openent/viescolaire/utils/ServicesHelper.java
- src/main/resources/jsonschema/multiteaching_update.json
- src/test/java/fr/openent/viescolaire/multiteaching/MultiTeachingServiceTest.java
https://entsupport.gdapublic.fr/browse/MVS-30
> feat(multiteaching): #MVS-30 Add substitute teachers to courses when setting multiteaching parameters

- src/main/java/fr/openent/viescolaire/controller/MultiTeachingController.java
- src/main/java/fr/openent/viescolaire/service/MultiTeachingService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultMultiTeachingService.java
https://entsupport.gdapublic.fr/browse/MVS-30
> fix(multiteaching): #MVS-30 prevent outOfBounds error + null eventbus

- src/main/java/fr/openent/viescolaire/service/impl/DefaultCommonCoursService.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/templates/viescolaire/param_edt.html
- Ajout de la page "Labels de cours" dans le paramétrage EDT
https://entsupport.gdapublic.fr/browse/MVS-46
> feat(edt-settings): #MVS-46 add EDT course tag settings page

- src/main/resources/public/sass/global/specifics/_memento.scss
- src/main/resources/public/sass/global/specifics/_mixins.scss
- src/main/resources/public/template/behaviours/sniplet-memento.html
Check
https://github.com/OPEN-ENT-NG/competences/pull/34
https://github.com/OPEN-ENT-NG/presences/pull/54
> feat(memento): #MVS-47 add sniplet notes in memento

- src/main/java/fr/openent/viescolaire/service/impl/DefaultCommonCoursService.java
- Ajout du champ `tagIds` dans les clés retournées du `DefaultCommonCoursService`
- 
https://entsupport.gdapublic.fr/browse/MVS-49
> fix(presences): #MVS-49 Add tagIds field in CommonCourseService results

- src/main/java/fr/openent/viescolaire/controller/EventBusController.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultTimeSlotService.java
- src/main/resources/public/modules/viescolaire/directives/timeslotAudience/timeslot-audience.ts
- src/main/resources/public/modules/viescolaire/models/common/TimeSlots.ts
Fix un problème de logique avec l'event bus + fix le front pour être multi étable
> fix(timeslot) #MVS-53 fix event bus getAudienceTimeslot

- src/main/java/fr/openent/viescolaire/core/enums/ServicesFieldEnum.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultServicesService.java
- src/test/java/fr/openent/viescolaire/service/impl/DefaultGroupeServiceTest.java
- src/test/java/fr/openent/viescolaire/service/impl/DefaultServicesServiceTest.java
Erreur dans un requête sql, on ne peut pas bind un champ de table
> fix(sql): #MVS-57 fix sql request

- deployment/viescolaire/migration/1.32.12/CoursesRecurrenceIndex.js
In production, a bug was found when you want to modify the recurrence of a lesson. This is due to a slowness coming from a mongo request. To solve the problem I made indexing the query fields to make it faster.
Modify the recurrence of a lesson
https://entsupport.gdapublic.fr/browse/MVS-60
> fix(courses): #MVS-60 fix slowness to get reccurence date

- deployment/viescolaire/migration/1.32.12/CoursesOccurencesIndex.js
- deployment/viescolaire/migration/1.32.12/CoursesTagsIndex.js
Slowness are spotted on the production. These indexes should improve performance.
Use EDT normally.
> improve(course): #MVS-59 improve course recovery

- LICENSE
- README.md
ajout d'une nouvelle licence et d'une description technique. Merge après vérification de PO.
> docs: #CO-1642 add new licence and technical description

- src/main/java/fr/openent/viescolaire/controller/EventBusController.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultTimeSlotService.java
- On rajoute une condition dans la récupération des timeslots sur une Map pour empêcher le NullPointerException
- On rajoute une vérification dans le handler du mongoDb.find() avec le Either
Ces erreurs ont été détectés dans les logs de Vertx
Pas de ticket, ce sont des fix/améliorations
> fix(unhandled): fix unhandled exception and npe

- src/main/java/fr/openent/viescolaire/controller/TrombinoscopeController.java
- src/main/java/fr/openent/viescolaire/core/constants/Field.java
- src/main/java/fr/openent/viescolaire/security/Trombinoscope/ManageTrombinoscope.java
Ajout d'un droit sur les api et vérification si l'utilisateur est dans la structure du trombinoscopes
Fix Magic string et remplacement des future déprécier.
Joué avec les trombinoscopes
Importer un trombinoscope
Afficher l'image d'un trombinoscope
Lier une image a un trombinoscope
Crée un trombinoscope en erreur
Afficher les trombinoscopes en erreur
Supprimée les trombinoscopes en erreur
Afficher les rapport des trombinoscopes 
[MVS-74](https://jira.support-ent.fr/browse/MVS-74)
> fix(security): #MVS-74 fix vulnerability TrombinoscopeController

- src/main/java/fr/openent/viescolaire/controller/GroupingController.java
- src/main/java/fr/openent/viescolaire/service/GroupingService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
- src/test/java/fr/openent/viescolaire/service/impl/DefaultGroupingServiceTest.java
Suppression d'une classe ou d'un regroupement appartenant au regroupement concerné.
https://confluence.support-ent.fr/display/MTVS/Contrat+d%27API
MVS-51: https://jira.support-ent.fr/browse/MVS-51
> feat(grouping):#MVS-51 delete audience from grouping

- src/main/java/fr/openent/viescolaire/controller/GroupingController.java
- src/main/java/fr/openent/viescolaire/service/GroupingService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
- src/test/java/fr/openent/viescolaire/service/impl/DefaultGroupingServiceTest.java
API pour la suppression d'un regroupement
https://confluence.support-ent.fr/display/MTVS/Contrat+d%27API
MVS-51: https://jira.support-ent.fr/browse/MVS-51
> feat(grouping):#MVS-51 delete grouping

- src/main/java/fr/openent/viescolaire/service/impl/DefaultClasseService.java
Une des classes était malformé, c'est a dire qu'elle ne contenait aucune info dans le neo4j. 
Cela provoqué des nullpointer lorsque l'on manipule cette classe.
Aller sur la page des paramétrage des période. Les classes s'affichent.
[MVS-76](https://jira.support-ent.fr/browse/MVS-76)
> fix(class): #MVS-76 fix nullpointer when retrieving malformed class

- src/main/java/fr/openent/viescolaire/controller/EventBusController.java
- src/main/java/fr/openent/viescolaire/controller/GroupingController.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
Ajout d'un event bus pour les grouping
Doc: https://confluence.support-ent.fr/display/MTVS/Contrat+d%27API
les tests ne passe pas car #54 doit être merge avant
Rien
> feat(grouping) #57 do event bus for grouping

- src/main/resources/public/modules/viescolaire/controllers/grouping.controller.ts
- src/main/resources/public/modules/viescolaire/directives/grouping/grouping-create/grouping-create.html
- src/main/resources/public/modules/viescolaire/directives/grouping/grouping-item/grouping-item.html
- src/main/resources/public/modules/viescolaire/directives/grouping/grouping-item/grouping-item.ts
- src/main/resources/public/modules/viescolaire/directives/grouping/grouping-list/grouping-list.html
- src/main/resources/public/modules/viescolaire/directives/grouping/grouping-list/grouping-list.ts
- src/main/resources/public/modules/viescolaire/models/__mocks__/entcore.ts
- src/main/resources/public/modules/viescolaire/models/common/Grouping.ts
- src/main/resources/public/modules/viescolaire/models/common/StudentDivision.ts
- src/main/resources/public/modules/viescolaire/services/__tests__/grouping.service.test.ts
- src/main/resources/public/modules/viescolaire/services/__tests__/timeslot-classe.service.test.ts
- src/main/resources/public/modules/viescolaire/services/__tests__/trombinoscope.service.test.ts
- src/main/resources/public/modules/viescolaire/services/grouping.service.ts
- src/main/resources/public/sass/global/components/_grouping-item.scss
- src/main/resources/public/sass/global/components/_index.scss
- src/main/resources/public/templates/viescolaire/param_etab_items/param-grouping.html
Adaptation du front a la doc + liaison entre le front et le back MVS-51 + correction des tests
Doc: https://confluence.support-ent.fr/display/MTVS/Contrat+d%27API#Contratd'API-addGroupingAudience
Depuis vie scolaire:
- pouvoir ajouter supprimer des grouping 
- pouvoir ajouter supprimer des group/classe dans les grouping
- pouvoir renommé un grouping
[MVS-51](https://jira.support-ent.fr/browse/MVS-51)
> feat(grouping): #MVS-51 make connection between back and front

- src/main/resources/i18n/fr.json
- src/main/resources/public/templates/viescolaire/param_competence.html
onglet competence dans viescolaire, premier menu
ajout d'une snipplet pour choisir le clacul des items de compétences
dépend de la PR sur la branche EVAL-334 du module competences [#110](https://github.com/OPEN-ENT-NG/competences/pull/110)
[EVAL-334](https://jira.support-ent.fr/browse/EVAL-334)
[MVS-73](https://jira.support-ent.fr/browse/MVS-73)
- [] Any dependent changes have been added to this project (must specify in **Description**)
> feat(competences):MVS-73 add snipplet StructureOptionIsAverageSkills

- build.gradle
- gradle.properties
- src/main/java/fr/openent/Viescolaire.java
- src/main/java/fr/openent/viescolaire/controller/EventBusController.java
- src/main/java/fr/openent/viescolaire/core/constants/Field.java
- src/main/java/fr/openent/viescolaire/helper/ModelHelper.java
- src/main/java/fr/openent/viescolaire/helper/UserHelper.java
- src/main/java/fr/openent/viescolaire/model/IModel.java
- src/main/java/fr/openent/viescolaire/model/Person/Student.java
- src/main/java/fr/openent/viescolaire/model/SlotModel.java
- src/main/java/fr/openent/viescolaire/model/Structure.java
- src/main/java/fr/openent/viescolaire/model/TimeslotModel.java
- src/main/java/fr/openent/viescolaire/service/ServiceFactory.java
- src/main/java/fr/openent/viescolaire/service/TimeSlotService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultTimeSlotService.java
- src/test/java/fr/openent/viescolaire/helper/ModelHelperTest.java
- src/test/java/fr/openent/viescolaire/service/impl/DefaultTimeSlotServiceTest.java
Add an event bus allow to retrieve the list of timeslot from a list of student id.
Add org.reflections:reflections:0.10.2 dependency for test
Doc: https://confluence.support-ent.fr/display/MTVS/TimeSlot+API
Nothing
[MVS-77](https://jira.support-ent.fr/browse/MVS-77)
> feat(timeslot): #MVS-77 add event bus to get timeslot by student

- src/main/java/fr/openent/viescolaire/service/impl/DefaultEleveService.java
Modification de la requête qui récupére les compéetneces notes d'un élève. Après plusieurs modifications de cette requête au cours du temps, l'union n'était plus utile.
le nombre de competences notes récupéré et le même que celui récupéré dans le menu suivi élève pour un élève donné et une période donnée ou un cycle
[MVS-78](https://jira.support-ent.fr/browse/MVS-78)
[EVAL-388](https://jira.support-ent.fr/browse/EVAL-388)
> fix(BilanCompetenceEleve): MVS-78 change get of a student's skills notes fix (EVAL-388)

- src/main/resources/public/modules/viescolaire/directives/grouping/grouping-create/grouping-create.html
- src/main/resources/public/modules/viescolaire/directives/grouping/grouping-item/grouping-item.html
- src/main/resources/public/modules/viescolaire/directives/grouping/grouping-item/grouping-item.ts
- src/main/resources/public/sass/global/components/_grouping-create.scss
- src/main/resources/public/sass/global/components/_index.scss
- src/main/resources/public/templates/viescolaire/param_etab_items/param-grouping.html
Modify the title: click on the pencil, I should have the Name of the group already written in the text box.
Modify the position of the "Create a group" button: place it to the right of the "Name" text field.
Go to the school life grouping page. The css changes are applied.
When editing a grouping, the name is entered directly.
[MVS-51](https://jira.support-ent.fr/browse/MVS-51)
> fix(grouping): #MVS-51 fix css and html

- src/main/resources/public/modules/viescolaire/directives/grouping/grouping-item/grouping-item.html
- src/main/resources/public/modules/viescolaire/directives/grouping/grouping-list/grouping-list.html
Orders the list of groupings and group on the groupings page.
Go to the page of groupings the list of groupings and groups remain in alphabetical order even if you add or remove them.
[MVS-51](https://jira.support-ent.fr/browse/MVS-51)
> fix(grouping): MSV-51 order grouping list and group list

- build.gradle
- gradle.properties
- src/main/java/fr/openent/Viescolaire.java
- src/main/java/fr/openent/viescolaire/controller/EventBusController.java
- src/main/java/fr/openent/viescolaire/core/constants/Field.java
- src/main/java/fr/openent/viescolaire/helper/ModelHelper.java
- src/main/java/fr/openent/viescolaire/helper/UserHelper.java
- src/main/java/fr/openent/viescolaire/model/IModel.java
- src/main/java/fr/openent/viescolaire/model/Person/Student.java
- src/main/java/fr/openent/viescolaire/model/SlotModel.java
- src/main/java/fr/openent/viescolaire/model/Structure.java
- src/main/java/fr/openent/viescolaire/model/TimeslotModel.java
- src/main/java/fr/openent/viescolaire/service/ServiceFactory.java
- src/main/java/fr/openent/viescolaire/service/TimeSlotService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultTimeSlotService.java
- src/test/java/fr/openent/viescolaire/helper/ModelHelperTest.java
- src/test/java/fr/openent/viescolaire/service/impl/DefaultGroupingServiceTest.java
- src/test/java/fr/openent/viescolaire/service/impl/DefaultTimeSlotServiceTest.java
Doit être merge après le tag 1.32.16.
> feat(timeslot): #MVS-77 add event bus to get timeslot by student (#62)

- src/main/java/fr/openent/Viescolaire.java
- src/main/java/fr/openent/viescolaire/controller/ServicesController.java
- src/main/java/fr/openent/viescolaire/service/ServicesService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultServicesService.java
Suptopic coefficient are now deleted when suppressing services.
Vie Scolaire -> Competences -> Modalité des services -> Delete a service and check in the DB if the subtopics linked to this service are not there.
[MVS-75](https://jira.support-ent.fr/browse/MVS-75)
> feat(services) : MVS-75 Suptopic coefficient are now deleted when suppressing services.

- src/main/java/fr/openent/viescolaire/service/impl/DefaultUserService.java
- src/test/java/fr/openent/viescolaire/service/impl/DefaultUserServiceTest.java
Ajout des nom des classes des utilisateurs dans l'event bus de recherche
Tester [MA-1015](https://jira.support-ent.fr/browse/MA-1015)
[MVS-79](https://jira.support-ent.fr/browse/MVS-79)
> feat(search): MVS-79 add user classes name in search user

- src/main/java/fr/openent/viescolaire/service/impl/DefaultClasseService.java
Gathered a new variable (displayName) from a class request for EVAL-398
[MVS-81](https://jira.support-ent.fr/browse/MVS-81)
> feat(classe) : MVS-81 Gathered a new variable (displayName) from a class request for EVAL-398.

- src/main/java/fr/openent/viescolaire/controller/TrombinoscopeController.java
- src/main/java/fr/openent/viescolaire/security/Trombinoscope/AccessTrombinoscope.java
Adding new security for trombinoscope. Now teacher, relative and student can see avatar (with conditions).
Teacher can see trombinoscope.
Relative can see trombinoscope of their children.
Student can only see his/her avatar.
Checklist to test :
- Teacher can access trombinoscope of their structure id
- Relative can access to trombinoscope of their children
- Student can access only to their avatar
[MSV-82](https://jira.support-ent.fr/browse/MVS-82)
> fix(trombinoscope): MSV-82 fix trombinoscope access with security

- src/main/java/fr/openent/viescolaire/controller/EventBusController.java
- src/main/java/fr/openent/viescolaire/controller/UserController.java
- src/main/java/fr/openent/viescolaire/security/StructureRight.java
- src/main/java/fr/openent/viescolaire/service/UserService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultUserService.java
- fixed the `/user/list` API returning info of all users
- check if Diary and EDT are starting properly with no issues
https://jira.support-ent.fr/browse/MVS-90
> fix(list-users): #MVS-90 fix list all users returning useless info + rights

- src/main/resources/public/modules/viescolaire/models/personnel/eval_niveau_comp.ts
Changing POST, UPDATE and DELETE front api on one model to fit competences's back resourceFilter
[#MVS-97](https://jira.support-ent.fr/browse/MVS-97)
> fix(security): #MVS-97 adding structure id to front api - linked with EVAL-458

- src/main/java/fr/openent/viescolaire/service/GroupeService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultClasseService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
Cette PR reprend la #80 qui a été livré en preprod avec un KO suite aux erreurs : 
```
2023-02-15 17:27:39 SEVERE Unhandled exception
java.util.NoSuchElementException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1471)
at java.util.HashMap$ValueIterator.next(HashMap.java:1498)
at fr.openent.viescolaire.service.impl.DefaultPeriodeService.lambda$null$8(DefaultPeriodeService.java:476)
at org.entcore.common.sql.SqlResult$6.handle(SqlResult.java:246)
at org.entcore.common.sql.SqlResult$6.handle(SqlResult.java:240)
at fr.wseduc.webutils.Utils.lambda$handlerToAsyncHandler$0(Utils.java:195)
```
On change l'algo en utilisant des streams pour faciliter le traitement des JsonArrays
- Module compétences -> Conseil de classe -> dans les critères, sélectionner une classe, période et un élève …
> fix(class): #MVS-100 fix ConcurrentModificationException + use stream

- src/main/java/fr/openent/viescolaire/service/impl/DefaultClasseService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultServicesService.java
Reprise de la PR #82 pour rectifier les problèmes de typo et corriger les manipulations de data handler
Ajout de la doc sur ce que peut renvoyer les handler
Rectification sur les commentaires de @FlorentMr sur la PR #82
Module compétences -> Conseil de classe -> dans les critères, sélectionner une classe, période et un élève = Tout ce flow ne doit pas rendre une page blanche avec des erreurs/pending de x min
Module compétences -> Conseil de classe -> Ne pas avoir de classe à sélectionner dans le cas où on a pas de classe "évaluable"
Tester également pour les groupes manuels (même mécanisme)
Vérifier qu'il n'y ait pas de KO quand on navigue dans Suivi élève -> choisir classe -> période -> élève 
https://jira.support-ent.fr/browse/EVAL-475
> fix: #MVS-100 fix evaluable groups

- src/main/java/fr/openent/viescolaire/controller/MultiTeachingController.java
- src/main/java/fr/openent/viescolaire/security/AccessIfMyStructureParamService.java
- src/main/java/fr/openent/viescolaire/security/AccessStructureAdminRightParamService.java
- src/main/java/fr/openent/viescolaire/security/StructureRight.java
- src/main/resources/public/modules/viescolaire/models/services/MultiTeaching.ts
- src/test/java/fr/openent/viescolaire/security/AccessIfMyStructureParamServiceTest.java
- src/test/java/fr/openent/viescolaire/security/AccessStructureAdminRightParamServiceTest.java
- src/test/java/fr/openent/viescolaire/security/StructureRightTest.java
Added security on this routes :
@Post("/multiteaching/create")
@Put("/multiteaching/update_visibility")
@Put("/multiteaching/update")
@Get("/mainteachers/:idStructure")
@Put("/multiteaching/delete")
Added parameters in front end request.
Module "Vie scolaire" -> Paramétrage des services -> "+" in column "Remplacement" or "Actions" -> add a co-teacher or replace teacher.
Test to create one, modify and delete.
For this route test : @Put("/multiteaching/update_visibility")
Module "Vie scolaire" -> tab "Compétences" -> "Modalités des services" -> in column "Enseignant" and "Remplacement" click on "eye" icon.
[MVS-102](https://jira.support-ent.fr/browse/MVS-102) in relation with [EVAL-486](https://jira.support-ent.fr/browse/EVAL-486) -> [PR](https://github.com/OPEN-ENT-NG/competences/pull/202)
> fix(security): #MVS-102 fixing security issues in MultiteachingController

- src/main/java/fr/openent/viescolaire/controller/ServicesController.java
- src/main/java/fr/openent/viescolaire/security/AccessIfMyStructureParamService.java
- src/test/java/fr/openent/viescolaire/security/AccessIfMyStructureParamServiceTest.java
Check on structure id and workflow right "viescolaire.paramServices" of getServices route of ServiceController 
[#MVS-112](https://jira.support-ent.fr/browse/MVS-112)
> fix(security): add resource filter on getServices route of ServicesController

- build.gradle
- src/main/java/fr/openent/viescolaire/controller/UserController.java
- src/main/java/fr/openent/viescolaire/core/constants/Field.java
- src/main/java/fr/openent/viescolaire/security/AdministratorRight.java
- src/main/java/fr/openent/viescolaire/security/WorkflowActionUtils.java
- src/main/java/fr/openent/viescolaire/security/WorkflowActions.java
- src/main/resources/public/modules/utils/functions/activeStructures.ts
- src/main/resources/public/modules/viescolaire/models/personnel/eval_niveau_comp.ts
> fix(security) : #MVS-96 - 97

- src/main/java/fr/openent/viescolaire/controller/ServicesController.java
- update ServicesController by replacing AccessIfMyStructureParamServices by AccessIfMyStructure
[#MVS-112](https://jira.support-ent.fr/browse/MVS-112)
> fix(security): #MVS-112 replace AccessIfMyStructureParamService by AccessIfMyStructure

- src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
INNER JOIN rel_type_periode to get oder
Périodes de tous les écrans
fix pour [EVAL-294](https://jira.support-ent.fr/browse/EVAL-294)
> fix(period): #MVS-119 add order in request

- build.sh
- package.json
- src/main/resources/public/modules/viescolaire/services/__tests__/trombinoscope.service.test.ts
- tsconfig.json
* fix les TU trombinoscopes
* Ajout script test node en mode "dev"
* Modification de la dépendance 
* **axios-mock : 1.21.2** : Eviter les erreurs `TS1192: Module '"/__w/vie-scolaire/vie-scolaire/node_modules/axios-mock-adapter/types/index"' has no default export./__w/vie-scolaire/vie-scolaire/src/main/resources/public/modules/viescolaire/services/__tests__/timeslot-classe.service.test.ts`
l'erreur est plus `has no default export` car la version axios actuel n'a pas d'export default
`./build.sh testNodeDev`
> fix(TU): fix trombinoscope angularJS

- src/main/java/fr/openent/viescolaire/controller/CoursController.java
Remove unused API according to the recommendations  of the documention within confluence.
@Get("/enseignant/:userId/:structureId/cours/:dateDebut/:dateFin") 
@Get("/cours/:etabId/:eleveId/:dateDebut/:dateFin/time/:timeDb/:timeFn")
@Get("/cours") 
@Post("/cours") 
All routes have been checked as not in use and this has been further confirmed by Flavien
[#MVS-105](https://jira.support-ent.fr/browse/MVS-105)
Nothing to test, only removed routes
> Fix(security): #MVS-105 remove unused API in CoursController

- src/main/java/fr/openent/viescolaire/controller/MementoController.java
- src/main/java/fr/openent/viescolaire/core/constants/Field.java
- src/main/java/fr/openent/viescolaire/security/memento/AccessMemento.java
- src/main/resources/public/modules/viescolaire/models/memento.model.ts
- src/main/resources/public/modules/viescolaire/services/MementoService.ts
- src/main/resources/public/modules/viescolaire/services/__tests__/memento.service.test.ts
- src/main/resources/public/modules/viescolaire/ts/memento/memento.ts
* Ajout de vérification côté API et côté client pour accéder au memento
* Vu avec l'équipe fonctionnelle pour dire qu'on doit être de profil **Personnel** ou **Enseignant** pour accéder aux APIs/clients memento
* Doc API : https://confluence.support-ent.fr/display/MTVS/Memento+API
En tant qu'enseignant/personnel : 
Aller sur présences -> accéder à la liste des événements -> cliquer un élève => On a accès au memento
Note : on peut aussi accéder à d'autres view où en cliquant sur l'élève on peut afficher le memento mais ça reste la même "entrée" de memento puisqu'on appelle tous la méthode `window.memento.load()` cf (https://github.com/OPEN-ENT-NG/vie-scolaire/blob/MVS-110/src/main/resources/public/modules/viescolaire/ts/memento/sniplet.ts#L15)
les APIs : 
``` …
```
> feat(memento): #MVS-110 add check access memento

- src/main/java/fr/openent/viescolaire/controller/EleveController.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultEleveService.java
Fix security on routes :
@Get("/enseignants")  => Removed because unused
@Get("/eleves") => update neo4j request to remove birthDate from query response and resource filter to check structure.
@Get("/users") => Removed because unused
@Get("/cycle/eleve/:idClasse") => SecuredAction authenticated actually fits well for this route
@Get("/structures/:structureId/students") => Resource filter to check structure.
[#MVS-107](https://jira.support-ent.fr/browse/MVS-107)
Only one route to test :
**@Get("/structures/:structureId/students")** => Vie scolaire => Etablissement => Trombinoscope
> Fix(security): #MVS-107 APIs security for EleveController part2

- src/main/java/fr/openent/Viescolaire.java
- src/main/java/fr/openent/viescolaire/controller/InitController.java
- src/main/java/fr/openent/viescolaire/core/constants/Field.java
- src/main/java/fr/openent/viescolaire/model/InitTeachers.java
- src/main/java/fr/openent/viescolaire/service/InitService.java
- src/main/java/fr/openent/viescolaire/service/ServiceFactory.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultInitService.java
- src/main/resources/sql/090-add-settings-init.sql
- src/test/java/fr/openent/viescolaire/service/impl/DefaultGroupingServiceTest.java
- src/test/java/fr/openent/viescolaire/service/impl/DefaultInitServiceTest.java
- src/test/java/fr/openent/viescolaire/service/impl/DefaultTimeSlotServiceTest.java
- add new API for checking teachers with no classes
- add new API for checking the initialization status of a structure
Related to https://github.com/OPEN-ENT-NG/presences/pull/296
API doc : https://confluence.support-ent.fr/display/MTVS/Init+API
- check the API routes are behaving properly: a response is received if the user has the proper rights.
https://jira.support-ent.fr/browse/MA-1067
> feat(MA-1067): add API to check of teachers unattached to classes

- src/main/java/fr/openent/Viescolaire.java
- src/main/java/fr/openent/viescolaire/controller/EventBusController.java
- src/main/java/fr/openent/viescolaire/controller/InitController.java
- src/main/java/fr/openent/viescolaire/service/InitService.java
- src/main/java/fr/openent/viescolaire/service/ServiceFactory.java
- src/main/java/fr/openent/viescolaire/service/TimeSlotService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultInitService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultTimeSlotService.java
- src/main/java/fr/openent/viescolaire/worker/InitWorker.java
- src/main/java/fr/openent/viescolaire/worker/InitWorker1D.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/jsonschema/init_structure.json
- src/test/java/fr/openent/viescolaire/service/impl/DefaultGroupingServiceTest.java
- src/test/java/fr/openent/viescolaire/service/impl/DefaultInitServiceTest.java
- src/test/java/fr/openent/viescolaire/service/impl/DefaultTimeSlotServiceTest.java
- add worker for initialisation 
- add auto generation of time slots
Doc API : https://confluence.support-ent.fr/display/MTVS/Init+API
- check if worker is launching properly 
- check if timeslots are properly generated + is auto selected in viescolaire settings
https://jira.support-ent.fr/browse/MA-999
> feat(MA-999): add init worker + generate timeslots

- README.md
- deployment/viescolaire/conf.j2
- src/main/java/fr/openent/Viescolaire.java
- src/main/java/fr/openent/viescolaire/core/constants/Field.java
- src/main/java/fr/openent/viescolaire/helper/MessageResponseHandler.java
- src/main/java/fr/openent/viescolaire/service/InitService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultInitService.java
- src/main/java/fr/openent/viescolaire/worker/InitWorker1D.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- added initialization function for default subject
- added new optional configuration key `"initDefaultSubject": ${initDefaultSubject}`
- Check if the initialisation creates a new subject called "Ecole" or with the name specified in viescolaire configuration.
https://jira.support-ent.fr/browse/MA-1000
> feat(MA-1000): add initialization of default subject

- src/main/java/fr/openent/viescolaire/core/constants/Field.java
- src/main/java/fr/openent/viescolaire/helper/TransactionHelper.java
- src/main/java/fr/openent/viescolaire/model/InitServiceModel.java
- src/main/java/fr/openent/viescolaire/model/SubjectModel.java
- src/main/java/fr/openent/viescolaire/model/TransactionElement.java
- src/main/java/fr/openent/viescolaire/service/InitService.java
- src/main/java/fr/openent/viescolaire/service/ServiceFactory.java
- src/main/java/fr/openent/viescolaire/service/ServicesService.java
- src/main/java/fr/openent/viescolaire/service/UserService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultInitService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultServicesService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultUserService.java
- src/main/java/fr/openent/viescolaire/worker/InitWorker.java
- src/main/java/fr/openent/viescolaire/worker/InitWorker1D.java
- add initialization of services for 1D from the neo4J teachers/classes
- check if the initialization of services generates services from the correct data
- check if service creation/update is still working properly
https://jira.support-ent.fr/browse/MA-1001
https://jira.support-ent.fr/browse/MVS-117
> feat(init-1D): #MA-1001 add initialization of services

- src/main/java/fr/openent/viescolaire/controller/PeriodeAnneeController.java
- src/main/java/fr/openent/viescolaire/core/constants/Field.java
- src/main/java/fr/openent/viescolaire/core/constants/PeriodeCode.java
- src/main/java/fr/openent/viescolaire/model/InitForm/InitFormSchoolYear.java
- src/main/java/fr/openent/viescolaire/model/Period.java
- src/main/java/fr/openent/viescolaire/service/PeriodeAnneeService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeAnneeService.java
- src/main/java/fr/openent/viescolaire/utils/DateHelper.java
- src/main/java/fr/openent/viescolaire/worker/InitWorker.java
- src/main/java/fr/openent/viescolaire/worker/InitWorker1D.java
- add initilization of the school year period from the init form data
- check that period creation/update is still working properly in vie-scolaire settings
- check that the school year dates have been properly modified/created from the init data
https://jira.support-ent.fr/browse/MA-1066
> feat(init-1D): #MA-1066 add init schoolyear period

- src/main/java/fr/openent/viescolaire/controller/ClasseController.java
EDT n'étais plus accessible pour les parents dû à cet endpoint et ça restriction excluant les parent.
Désormais on se contente de vérifier que l'utilisateur a le droit d'accès à l'établissement. 
[Jira - MVS-122](https://jira.support-ent.fr/browse/MVS-122)
> Fix(security): #MVS-122 fix /classes endpoint that not more require to filter on profile

- src/main/java/fr/openent/Viescolaire.java
- src/main/java/fr/openent/viescolaire/core/constants/Field.java
- src/main/java/fr/openent/viescolaire/service/InitService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultInitService.java
- src/main/java/fr/openent/viescolaire/worker/InitWorker1D.java
- add init of exclusion periods to init worker
- check if the periods have been properly initialized from the init form settings (zone A, B, C or else)
https://jira.support-ent.fr/browse/MA-1066
> feat(init-1D): #MA-1066 add init exclusion periods

- src/main/java/fr/openent/viescolaire/core/constants/Field.java
- src/main/java/fr/openent/viescolaire/helper/FutureHelper.java
- src/main/java/fr/openent/viescolaire/model/Audience.java
- src/main/java/fr/openent/viescolaire/service/InitService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultInitService.java
- src/main/java/fr/openent/viescolaire/worker/InitWorker.java
- src/main/java/fr/openent/viescolaire/worker/InitWorker1D.java
- added initialization of courses for first degree
- check if launching the presences initialization if creating courses matching the data from viescolaire services
https://jira.support-ent.fr/browse/MA-1002
https://jira.support-ent.fr/browse/MVS-125
> feat(init-1D): #MVS-125 add initialization of courses

- gulpfile.js
- src/main/java/fr/openent/viescolaire/core/constants/Field.java
- src/main/java/fr/openent/viescolaire/worker/InitWorker.java
- src/main/resources/i18n/timeline/en.json
- src/main/resources/i18n/timeline/fr.json
- src/main/resources/jsonschema/init_structure.json
- src/main/resources/view-src/notify/initialization_done.html
- src/main/resources/view-src/notify/initialization_done.json
- src/main/resources/view-src/notify/initialization_error.html
- src/main/resources/view-src/notify/initialization_error.json
- added success/error timeline notification at the end of the initialization process
- fixed jsonSchema
- check that a new notification is added after the initilization is complete
https://jira.support-ent.fr/browse/MVS-127
> feat(init-1D): #MVS-127 add timeline notification for the end process

- src/main/java/fr/openent/Viescolaire.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultInitService.java
- src/main/java/fr/openent/viescolaire/service/impl/VieScolaireRepositoryEvents.java
- added reset of initialization status on the year transition event
- check if the transition event allow the init form to be displayed again (this can be tester through the API : https://confluence.support-ent.fr/pages/viewpage.action?pageId=67214467)
https://jira.support-ent.fr/browse/MVS-128
> feat(init-1D): #MVS-128 reset initialization status on year transition

- src/main/java/fr/openent/viescolaire/service/impl/DefaultInitService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultUserService.java
- add classes from neo4j relationships (not only the classes field) for creating services
- check if all teachers have an associated service with after 1D initialization
https://jira.support-ent.fr/browse/MVS-117
> fix(init-1D): #MVS-117 add classes from neo4j relationships for services

- src/main/java/fr/openent/viescolaire/service/impl/DefaultEleveService.java
ajout du champs formative dans le réponse de la requête qui récupère les devoirs avec une annotation.
avec des évaluations formatives et des annotations sur ces évaluations
la lettre F doit-être présente à côté de la note issue d'une évaluation et la note ne doit pas être pris en compte dans le calcule de la moyenne
avec un ce ou un prof
suivi élève -> onglet suivi des notes le front et les deux exports liés.
pour un élève ou un parent -> relevé périodique et l'export
[MVS-129](https://jira.support-ent.fr/browse/MVS-129) et [EVAL-520](https://jira.support-ent.fr/browse/EVAL-520)
> fix(followupStudent): #MVS-129 add formative type in query response

- src/main/java/fr/openent/viescolaire/service/impl/DefaultUserService.java
Makes it possible to search with firstname AND lastname + list now only shows students with firstname or lastname beginning with the occurence in the textbox.
Présences -> Publipostage -> Filtres (à gauche de la liste d'absences) -> Taper dans la textbox un ou des caractères et vérifier que les noms et prénoms de cette occurence de caractères sont bien listés.
Possibles vérifications à faire au niveau d'autres textbox liés à "users.search" de viescolaire
[MVS-124](https://jira.support-ent.fr/browse/MVS-124)
lié à [MA-1051](https://jira.support-ent.fr/browse/MA-1051)
> feat(search) : #MVS-124 Makes it possible to search with firstname AND lastname.

- deployment/viescolaire/conf.json.template
Modification de la date à partir de laquelle on considère la fin du mouvement des élèves (en config), pour l'année scolaire 2023
[MVS-131](https://jira.support-ent.fr/browse/MVS-131)
> feat(transition): #MVS-131 update enable-date from which we consider students movement.

- src/main/java/fr/openent/viescolaire/controller/EventBusController.java
- src/main/java/fr/openent/viescolaire/service/TimeSlotService.java
- src/main/java/fr/openent/viescolaire/service/impl/DefaultTimeSlotService.java
Fix mobile API NPE with timeslots sometimes being badly gotten because of multiple structures on one student.
cf ticket MA-1062
[MVS-134](https://jira.support-ent.fr/browse/MVS-134)
[MA-1062](https://jira.support-ent.fr/browse/MA-1062)
> fix(mobile) : #MVS-134 fix mobile API NPE with timeslots sometimes being badly gotten because of multiple structures on one student.

- src/main/java/fr/openent/viescolaire/service/impl/DefaultEleveService.java
Adds retrieval of reponsables ids for Presences notifications.
[MVS-136](https://jira.support-ent.fr/browse/MVS-136)
linked to [MA-1140](https://jira.support-ent.fr/browse/MA-1140)
> feat(eleve) : #MVS-136 Adds retrieval of reponsables ids.

- src/main/java/fr/openent/Viescolaire.java
- src/main/java/fr/openent/viescolaire/controller/FakeRight.java
- src/main/resources/public/modules/viescolaire/ts/behaviours.ts
- src/main/resources/public/modules/viescolaire/ts/memento/memento.ts
- src/main/resources/public/modules/viescolaire/ts/rights.ts
- src/main/resources/public/template/behaviours/sniplet-memento.html
- added a viescolaire.1d workflow right for hiding html elements on 1D structures
- hid incidents panel in memento for 1D
- hid competences panel in memento for 1D
- check if every panel is displayed properly in memento w/o the 1d right
- check if incident and competences panels are hidden if the right is activated
https://jira.support-ent.fr/browse/MVS-142
> fix(memento): #MVS-142 added viescolaire.1d right and adapt display

- src/main/resources/i18n/timeline/en.json
- src/main/resources/i18n/timeline/fr.json
Add label for external notifications (in timeline)
Check in your account, in the external notifications panel, if labels are correctly set
https://jira.support-ent.fr/browse/MVS-144
> feat(timeline): #MVS-144 add labels for external notification
